In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = ({
    "Age": [22, 25, 28, 35, 40, 45, 50, 23, 31, 37, 42, 48, 55, 29, 33, 39, 44, 52, 26, 36],
    "Income": [18000, 22000, 30000, 45000, 60000, 75000, 90000, 20000, 35000, 50000, 65000, 80000, 95000, 28000, 42000, 58000, 70000, 85000, 24000, 52000],
    "Credit_Score": [520, 560, 610, 680, 720, 750, 790, 540, 630, 690, 730, 760, 800, 600, 670, 710, 740, 780, 580, 700],
    "Loan_Amount": [15000, 18000, 20000, 25000, 30000, 35000, 40000, 17000, 22000, 27000, 32000, 37000, 42000, 21000, 26000, 31000, 36000, 41000, 19000, 29000],
    "Employment_Years": [1, 2, 3, 6, 8, 10, 15, 1, 4, 7, 9, 12, 18, 3, 5, 8, 11, 16, 2, 7],
    "Existing_Debt": [9000, 8000, 7000, 5000, 4000, 3000, 2000, 8500, 6500, 4500, 3500, 2500, 1500, 7200, 5200, 3800, 2800, 1800, 7800, 4300],
    "Loan_Status": [
        "Rejected", "Rejected", "Rejected", "Approved", "Approved",
        "Approved", "Approved", "Rejected", "Rejected", "Approved",
        "Approved", "Approved", "Approved", "Rejected", "Approved",
        "Approved", "Approved", "Approved", "Rejected", "Approved"
    ]
})

df = pd.DataFrame(data)
df

,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Debt,Loan_Status
0,22,18000,520,15000,1,9000,Rejected
1,25,22000,560,18000,2,8000,Rejected
2,28,30000,610,20000,3,7000,Rejected
3,35,45000,680,25000,6,5000,Approved
4,40,60000,720,30000,8,4000,Approved
5,45,75000,750,35000,10,3000,Approved
6,50,90000,790,40000,15,2000,Approved
7,23,20000,540,17000,1,8500,Rejected
8,31,35000,630,22000,4,6500,Rejected
9,37,50000,690,27000,7,4500,Approved
10,42,65000,730,32000,9,3500,Approved
11,48,80000,760,37000,12,2500,Approved
12,55,95000,800,42000,18,1500,Approved
13,29,28000,600,21000,3,7200,Rejected
14,33,42000,670,26000,5,5200,Approved
15,39,58000,710,31000,8,3800,Approved
16,44,70000,740,36000,11,2800,Approved
17,52,85000,780,41000,16,1800,Approved
18,26,24000,580,19000,2,7800,Rejected
19,36,52000,700,29000,7,4300,Approved

In [18]:
df.head()

,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Debt,Loan_Status
0,22,18000,520,15000,1,9000,Rejected
1,25,22000,560,18000,2,8000,Rejected
2,28,30000,610,20000,3,7000,Rejected
3,35,45000,680,25000,6,5000,Approved
4,40,60000,720,30000,8,4000,Approved

In [19]:
from sklearn.tree import DecisionTreeClassifier

X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']

In [20]:
model = DecisionTreeClassifier()
model.fit(X,y)

new_customer = pd.DataFrame({
    "Age": [30],
    "Income": [40000],
    "Credit_Score": [650],
    "Loan_Amount": [24000],
    "Employment_Years": [4],
    "Existing_Debt": [6000]
})

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
pred = model.predict(new_customer)
print(pred)

['Rejected']

In [23]:
pred = model.predict(X_test)
print(pred)

['Rejected' 'Approved' 'Approved' 'Rejected']

In [24]:
from sklearn.metrics import  accuracy_score

In [27]:
accuracy = accuracy_score(y_test, pred)
accuracy

1.0

In [28]:
print('Prediected',pred)
print('Actual', list(y_test))
print('Accuracy', accuracy)

Prediected ['Rejected' 'Approved' 'Approved' 'Rejected']
Actual ['Rejected', 'Approved', 'Approved', 'Rejected']
Accuracy 1.0

In [31]:
len(y)

20